image: Visual Studio 2017

platform:
- x64

configuration:
  - Release
  - Debug

matrix:
  fast_finish: true

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user
  - cmd: conan remote add --force d34dpkgs https://api.bintray.com/conan/0xd34d10cc/d34dpkgs
  - cmd: conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: conan config set storage.path=c:\Users\appveyor\conanCache
  - cmd: mkdir %configuration%
  - cmd: cd %configuration%

build_script:
  - cmd: conan install .. --build=missing -s build_type=%configuration%
  - cmd: set generator=Visual Studio 15 2017 Win64
  - cmd: cmake .. -G"%generator%"
  - cmd: cmake --build . --target ALL_BUILD --config %configuration%

test_script:
  - ctest -C %configuration% -T Test
  - ../scripts/upload-ctest-report.ps1

cache:
  - C:\Users\Appveyor\.conan -> conanfile.py
  - C:\.conan -> conanfile.py
  - C:\Users\Appveyor\conanCache -> conanfile.py