image: Visual Studio 2019

branches:
  only:
    - master

platform:
  - x64

configuration:
  - Release
  - Debug

install:
  - cmd: set PATH=C:\Python38-x64\Scripts\;%PATH%
  - cmd: pip.exe install conan
  - cmd: conan remote add --force d34dpkgs https://api.bintray.com/conan/0xd34d10cc/d34dpkgs
  - cmd: conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: mkdir %configuration%
  - cmd: cd %configuration%

build_script:
  - cmd: conan install .. --build=missing -s build_type=%configuration%
  - cmd: set generator=Visual Studio 16 2019
  - cmd: cmake .. -G"%generator%"
  - cmd: cmake --build . --target ALL_BUILD --config %configuration%

test_script:
  - ctest -C %configuration%

cache:
  - '%userprofile%\.conan -> conanfile.py'
  - C:\.conan -> conanfile.py