sudo: required

language: cpp

cache:
  - directories: /home/travis/.conan
  - ccache

compiler: 
  - clang

os: linux
addons: &clang5
  apt:
    packages:
      - g++-6
      - clang-6.0
    sources: 
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/cmake-download/bin:$PATH"

before_script:
  - mkdir cmake-download && cd cmake-download && curl -O https://cmake.org/files/v3.12/cmake-3.12.0-rc1-Linux-x86_64.sh
    && bash cmake-3.12.0-rc1-Linux-x86_64.sh --skip-license && cd ..
  - sudo pip install conan
  - sudo apt-get install libxtst-dev libxinerama-dev libx11-dev libxfixes-dev libxrandr-dev libxcursor-dev
  - conan remote add --force d34dpkgs https://api.bintray.com/conan/0xd34d10cc/d34dpkgs
  - conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - mkdir build
  - cd build
  - conan install --build=missing  .. 
  - cmake -D CMAKE_CXX_COMPILER="ccache" -D CMAKE_CXX_COMPILER_ARG1="clang++" -D CMAKE_C_COMPILER="ccache" -D CMAKE_C_COMPILER_ARG1="clang" ..
  - make

notifications:
  email: false
