# Based on https://github.com/Microsoft/GSL/blob/master/.travis.yml

language: cpp
sudo: false

notifications:
  email: false

cache:
  directories:
    - $HOME/.conan

matrix:
  include:
    # OS X
    - env: CC=clang CXX=clang++ BUILD_TYPE=Debug STDLIB=libc++ LINKER=ld
      os: osx
      osx_image: xcode11.5
      compiler: clang

    - env: CC=clang CXX=clang++ BUILD_TYPE=Release STDLIB=libc++ LINKER=ld
      os: osx
      osx_image: xcode11.5
      compiler: clang

    # Linux
    - env: CC=clang-9 CXX=clang++-9 BUILD_TYPE=Debug STDLIB=libc++ LINKER=lld-9
      os: linux
      dist: bionic
      addons: &clang9
        apt:
          packages:
            # toolchain & build tools
            - clang-9
            - lld-9
            - libc++-9-dev
            - libc++abi-9-dev
            - cmake
            # OpenGL
            - libgl1-mesa-dev
            # for conan
            - python3-pip 
            # screen capture dependencies
            - libxtst-dev 
            - libxinerama-dev 
            - libx11-dev 
            - libxfixes-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: CC=clang-9 CXX=clang++-9 BUILD_TYPE=Release STDLIB=libc++ LINKER=lld-9
      os: linux
      dist: bionic
      addons: *clang9

install:
  - export CXXFLAGS="-stdlib=${STDLIB} ${CXXFLAGS}"
  - export LDFLAGS="-fuse-ld=${LINKER} ${LDFLAGS}"

  # Travis machines have 2 cores
  - JOBS=2
  - cmake --version
  - ${CXX} --version
  - ${CC} --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - sudo pip install conan
  
  # setup conan remotes
  - conan remote add --force d34dpkgs https://api.bintray.com/conan/0xd34d10cc/d34dpkgs
  - conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  
  # build dependencies
  - mkdir build && cd build
  - conan install --build=missing -s build_type=$BUILD_TYPE -s compiler.libcxx=$STDLIB ..
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  # build and run tests
  - cmake --build . -- -j${JOBS}
  # TODO
  # - ctest --output-on-failure -j${JOBS}
