# Based on https://github.com/Microsoft/GSL/blob/master/.travis.yml

language: cpp
sudo: false

notifications:
  email: false

cache:
  directories:
    - $HOME/.conan

matrix:
  include:
    # OS X
    - env: CC=clang CXX=clang++ BUILD_TYPE=Debug STDLIB=libc++ LINKER=ld
      os: osx
      osx_image: xcode11.5
      compiler: clang

    - env: CC=clang CXX=clang++ BUILD_TYPE=Release STDLIB=libc++ LINKER=ld
      os: osx
      osx_image: xcode11.5
      compiler: clang

    # Linux
    - env: CC=clang-9 CXX=clang++-9 BUILD_TYPE=Debug STDLIB=libc++ LINKER=lld-9
      os: linux
      dist: bionic
      addons: &clang9
        apt:
          packages:
            # llvm 9.0 toolchain
            - clang-9
            - lld-9
            - libc++-9-dev
            - libc++abi-9-dev
            # OpenGL
            - libgl1-mesa-dev
            # for conan
            - python3-pip 
            # screen capture dependencies
            - libxtst-dev 
            - libxinerama-dev 
            - libx11-dev 
            - libxfixes-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: CC=clang-9 CXX=clang++-9 BUILD_TYPE=Release STDLIB=libc++ LINKER=lld-9
      os: linux
      dist: bionic
      addons: *clang9

install:
  - export CC=${CC}
  - export CXX=${CXX}
  - export CXXFLAGS="-stdlib=${STDLIB} ${CXXFLAGS}"
  - export LDFLAGS="-fuse-ld=${LINKER} ${LDFLAGS}"
 
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - CMAKE_VERSION=3.13.4
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - cmake --version
  - ${CXX} --version
  - ${CC} --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - sudo pip install conan
  
  # setup conan remotes
  - conan remote add --force d34dpkgs https://api.bintray.com/conan/0xd34d10cc/d34dpkgs
  - conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  
  # build dependencies
  - mkdir build && cd build
  - conan install --build=missing -s build_type=$BUILD_TYPE -s compiler.libcxx=$STDLIB ..
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  # build and run tests
  - cmake --build . -- -j${JOBS}
  # TODO
  # - ctest --output-on-failure -j${JOBS}
