[package]
name = "shar"
version = "0.1.0"
authors = ["0xd34d10cc <0xd34d10cc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.1.1", features = ["image", "tokio"] }
scrap = "0.5.0"
anyhow = "1.0.31"
tokio = { version = "0.2.21", features = ["time", "sync", "stream"] }
log = "0.4.8"
env_logger = "0.7.1"
dotenv = "0.15.0"
iced_native = "0.2.2"
futures = "0.3.5"
